'use client';

import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { PromptRewriteRequestSchema, PromptRewriteRequest, PromptRewriteResponse } from '../schemas';
import { GoogleGenAI, Type } from '@google/genai';
import { Loader2, Sparkles, Copy, Check, Save } from 'lucide-react';
import { useTemplates } from '@/features/templates/store';
import { useHistory } from '@/features/history/store';

export function PromptEngineerForm() {
  const [result, setResult] = useState<PromptRewriteResponse | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  const [saved, setSaved] = useState(false);
  const { saveTemplate } = useTemplates();
  const { addHistoryItem } = useHistory();

  const { register, handleSubmit, formState: { isSubmitting, errors } } = useForm<PromptRewriteRequest>({
    resolver: zodResolver(PromptRewriteRequestSchema),
  });

  const onSubmit = async (data: PromptRewriteRequest) => {
    setError(null);
    setResult(null);
    
    try {
      const ai = new GoogleGenAI({ apiKey: process.env.NEXT_PUBLIC_GEMINI_API_KEY });
      
      const systemInstruction = `You are an expert AI Prompt Engineer. Your goal is to take a user's basic prompt and rewrite it into a highly optimized, expert-level prompt.
      Consider the following optional constraints if provided:
      - Audience: ${data.audience || 'General'}
      - Tone: ${data.tone || 'Professional'}
      - Format: ${data.format || 'Any'}
      
      Identify any potential variables in the optimized prompt and list them. Variables should be enclosed in curly braces, e.g., {topic}.
      `;

      const response = await ai.models.generateContent({
        model: 'gemini-3.1-pro-preview',
        contents: `Rewrite the following prompt to be more effective:\n\n${data.prompt}`,
        config: {
          systemInstruction,
          responseMimeType: 'application/json',
          responseSchema: {
            type: Type.OBJECT,
            properties: {
              optimizedPrompt: {
                type: Type.STRING,
                description: "The rewritten, highly optimized prompt.",
              },
              explanation: {
                type: Type.STRING,
                description: "A brief explanation of why this new prompt is better.",
              },
              variables: {
                type: Type.ARRAY,
                items: { type: Type.STRING },
                description: "A list of variables used in the optimized prompt (e.g., ['topic', 'audience']).",
              },
            },
            required: ["optimizedPrompt", "explanation", "variables"],
          },
        },
      });

      if (!response.text) {
        throw new Error("No response from AI");
      }

      const parsedResult = JSON.parse(response.text) as PromptRewriteResponse;
      setResult(parsedResult);
      
      addHistoryItem({
        type: 'engineer',
        prompt: data.prompt,
        result: parsedResult.optimizedPrompt,
      });
    } catch (err) {
      console.error("Error rewriting prompt:", err);
      setError(err instanceof Error ? err.message : "An unknown error occurred");
    }
  };

  const copyToClipboard = () => {
    if (result) {
      navigator.clipboard.writeText(result.optimizedPrompt);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleSaveTemplate = () => {
    if (result) {
      const newTemplate = {
        id: crypto.randomUUID(),
        name: `Optimized Prompt ${new Date().toLocaleDateString()}`,
        description: 'Generated by AI Prompt Engineer',
        content: result.optimizedPrompt,
        variables: result.variables,
        createdAt: new Date().toISOString(),
      };
      saveTemplate(newTemplate);
      setSaved(true);
      setTimeout(() => setSaved(false), 2000);
    }
  };

  return (
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
      <div className="bg-white p-6 rounded-xl shadow-sm border border-slate-200">
        <h2 className="text-xl font-semibold mb-4 text-slate-900 flex items-center gap-2">
          <Sparkles className="w-5 h-5 text-indigo-500" />
          Prompt Engineer
        </h2>
        <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
          <div>
            <label className="block text-sm font-medium text-slate-700 mb-1">Basic Prompt</label>
            <textarea
              {...register('prompt')}
              className="w-full h-32 p-3 rounded-lg border border-slate-300 focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 resize-none font-mono text-sm"
              placeholder="e.g., Write a blog post about AI."
            />
            {errors.prompt && <p className="text-red-500 text-sm mt-1">{errors.prompt.message}</p>}
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div>
              <label className="block text-sm font-medium text-slate-700 mb-1">Audience (Optional)</label>
              <input
                {...register('audience')}
                type="text"
                className="w-full p-2 rounded-lg border border-slate-300 focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 text-sm"
                placeholder="e.g., Beginners"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-slate-700 mb-1">Tone (Optional)</label>
              <input
                {...register('tone')}
                type="text"
                className="w-full p-2 rounded-lg border border-slate-300 focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 text-sm"
                placeholder="e.g., Professional"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-slate-700 mb-1">Format (Optional)</label>
              <input
                {...register('format')}
                type="text"
                className="w-full p-2 rounded-lg border border-slate-300 focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 text-sm"
                placeholder="e.g., Markdown"
              />
            </div>
          </div>

          <button
            type="submit"
            disabled={isSubmitting}
            className="w-full py-2.5 px-4 bg-indigo-600 hover:bg-indigo-700 text-white font-medium rounded-lg transition-colors flex items-center justify-center gap-2 disabled:opacity-70"
          >
            {isSubmitting ? <Loader2 className="w-5 h-5 animate-spin" /> : <Sparkles className="w-5 h-5" />}
            {isSubmitting ? 'Optimizing...' : 'Optimize Prompt'}
          </button>
        </form>
        {error && (
          <div className="mt-4 p-3 bg-red-50 text-red-700 rounded-lg text-sm border border-red-200">
            {error}
          </div>
        )}
      </div>

      <div className="bg-slate-50 p-6 rounded-xl border border-slate-200 h-full min-h-[400px]">
        {result ? (
          <div className="space-y-6 h-full flex flex-col">
            <div className="flex-1">
              <div className="flex items-center justify-between mb-2">
                <h3 className="text-sm font-semibold text-slate-500 uppercase tracking-wider">Optimized Prompt</h3>
                <div className="flex items-center gap-2">
                  <button
                    onClick={handleSaveTemplate}
                    className="p-1.5 text-slate-500 hover:text-indigo-600 hover:bg-indigo-50 rounded-md transition-colors flex items-center gap-1 text-xs font-medium"
                    title="Save to templates"
                  >
                    {saved ? <Check className="w-4 h-4 text-emerald-500" /> : <Save className="w-4 h-4" />}
                    {saved ? 'Saved' : 'Save'}
                  </button>
                  <button
                    onClick={copyToClipboard}
                    className="p-1.5 text-slate-500 hover:text-indigo-600 hover:bg-indigo-50 rounded-md transition-colors flex items-center gap-1 text-xs font-medium"
                    title="Copy to clipboard"
                  >
                    {copied ? <Check className="w-4 h-4 text-emerald-500" /> : <Copy className="w-4 h-4" />}
                    {copied ? 'Copied' : 'Copy'}
                  </button>
                </div>
              </div>
              <div className="bg-white p-4 rounded-lg border border-slate-200 font-mono text-sm text-slate-800 whitespace-pre-wrap shadow-sm">
                {result.optimizedPrompt}
              </div>
            </div>

            <div>
              <h3 className="text-sm font-semibold text-slate-500 uppercase tracking-wider mb-2">Why it&apos;s better</h3>
              <p className="text-slate-700 text-sm bg-indigo-50/50 p-3 rounded-lg border border-indigo-100">
                {result.explanation}
              </p>
            </div>

            {result.variables.length > 0 && (
              <div>
                <h3 className="text-sm font-semibold text-slate-500 uppercase tracking-wider mb-2">Variables Detected</h3>
                <div className="flex flex-wrap gap-2">
                  {result.variables.map((v, i) => (
                    <span key={i} className="px-2.5 py-1 bg-slate-200 text-slate-700 text-xs font-medium rounded-full">
                      {'{'}{v}{'}'}
                    </span>
                  ))}
                </div>
              </div>
            )}
          </div>
        ) : (
          <div className="h-full flex flex-col items-center justify-center text-slate-400 space-y-4">
            <Sparkles className="w-12 h-12 opacity-20" />
            <p className="text-center text-sm max-w-xs">
              Enter a basic prompt on the left, and the AI Prompt Engineer will rewrite it into an expert-level prompt here.
            </p>
          </div>
        )}
      </div>
    </div>
  );
}
